<?php
declare(strict_types=1);

namespace App\Services;

use PDO;
use PDOException;

/**
 * Detects whether the app is already installed, so install.php can safely
 * be re-run without blindly overwriting an existing installation.
 */
class InstallState
{
    public static function isLocked(): bool
    {
        return is_file(APP_INSTALL_LOCK) && is_file(APP_CONFIG_FILE);
    }

    public static function configExists(): bool
    {
        return is_file(APP_CONFIG_FILE);
    }

    /**
     * True only when config.php exists AND we can actually connect and see
     * the schema — protects against a half-finished / corrupted install.
     */
    public static function isFullyInstalled(): bool
    {
        if (!self::configExists()) {
            return false;
        }
        require_once APP_CONFIG_FILE;
        try {
            $pdo = Database::connection();
            $stmt = $pdo->query("SHOW TABLES LIKE 'merchants'");
            return $stmt !== false && $stmt->fetch() !== false;
        } catch (PDOException $e) {
            return false;
        }
    }

    public static function writeLock(): void
    {
        file_put_contents(APP_INSTALL_LOCK, json_encode([
            'installed_at' => date('c'),
            'app_version' => '1.0.0',
        ], JSON_PRETTY_PRINT));
    }

    public static function removeLock(): void
    {
        if (is_file(APP_INSTALL_LOCK)) {
            unlink(APP_INSTALL_LOCK);
        }
    }

    public static function writeConfig(string $host, string $port, string $name, string $user, string $pass): void
    {
        $appKey = bin2hex(random_bytes(32));
        $tpl = <<<PHP
<?php
// Generated by install.php on %s — do not commit this file to version control.
declare(strict_types=1);

if (!defined('DB_HOST')) define('DB_HOST', %s);
if (!defined('DB_PORT')) define('DB_PORT', %s);
if (!defined('DB_NAME')) define('DB_NAME', %s);
if (!defined('DB_USER')) define('DB_USER', %s);
if (!defined('DB_PASS')) define('DB_PASS', %s);
if (!defined('APP_KEY')) define('APP_KEY', %s);
PHP;
        $content = sprintf(
            $tpl,
            date('c'),
            var_export($host, true),
            var_export($port, true),
            var_export($name, true),
            var_export($user, true),
            var_export($pass, true),
            var_export($appKey, true)
        );
        file_put_contents(APP_CONFIG_FILE, $content);
    }
}
